### PR TITLE
add: documentation and exercise for CI/CD

### PR DESCRIPTION
**Pull request by saumyabakshi**

### CODE REVIEW

**Comment by saumyabakshi** [comment]
The [MR ](https://gitlab.com/vernacularai/kubernetes/k8s-configs/-/merge_requests/1151) in k8s-configs with the changes.
The [repo](https://gitlab.com/vernacularai/starter-sample) in gitlab with the suggested changes.

**Comment by PrateeksGitHub** [comment]
Hey Saumya! These are my observations after going through the doc:

- If the doc is intended to be an introductory hands-on tutorial on our CI/CD flows (and not a document to get familiar with the concepts being used in the exercises), it is doing a good job.
- The Outline link on line 6 seems to lead to a document that seems incomplete. Please review that link to make sure it is pointing to the correct document. (which I believe may be [this](https://outline.skit.ai/doc/1how-to-build-and-deploy-xBNzAKeb02)).

Have committed an edit with some minor typing error fixes. Hope this was helpful! :)

**Comment by saumyabakshi** [comment]
Do you think I should add a brief explanation of Gitlab, Chartmuseum and ArgoCD in the beginning of one of the documents ?

**Comment by PrateeksGitHub** [comment]
In my opinion, an explanation of these platforms is not needed in the document. At most, you can add links to their websites, but those are easy to look up on the internet anyway. If there is information like why we use these particular platforms, or what is specifically being accomplished by each of these, then that will be more useful.

**Pull request merged**
