### PR TITLE
docs: http api basics

### PR DESCRIPTION
**Pull request by vabshere**

### CODE REVIEW

**Review by Sharan-Skit — COMMENTED** [review]
This is an amazing doc. No suggestions from my side as of now.

**Comment by vabshere** [comment]
thanks a lot @Sharan-Skit 
i'll be adding an interactive exercise soon
do check that out too

**Comment by PrateeksGitHub** [comment]
- A working example of a basic HTTP based interaction (ideally something that one might use at Skit) might improve the understanding of the concepts of the reader. At the moment, the article is too abstract IMO.
- Leaving out details similar to “HTTP is stateless” or “HTTP methods are nouns, but can be verbs”, and replacing them with an explanation from the said example might be more helpful for the reader.
- The line: “HTTP header fields...the internet system.” does not clearly explain the purpose of Headers.
- Again, adding an example and reducing texts that seem like “fun facts” might benefit the HTTP with REST section.
- Hyperlinking of text to be completed.
- The length and content structure of the document seems very well suited for a new joiner wanting to get introduced to the topic, while having an option to explore deeper with the hyperlinked resources within the article.

P.S. Just read that @vabshere will be adding an interactive example, so that's awesome!

**Comment by vabshere** [comment]
Hi @PrateeksGitHub 
Your pointers are helpful and appreciated. They also point out some concerns I have with the present document too. Please go through my addressal of the same so we may further improve it

> * A working example of a basic HTTP based interaction (ideally something that one might use at Skit) might improve the understanding of the concepts of the reader. At the moment, the article is too abstract IMO.

As you noted, adding an interactive exercise should suffice for this.

> * Leaving out details similar to “HTTP is stateless” or “HTTP methods are nouns, but can be verbs”, and replacing them with an explanation from the said example might be more helpful for the reader.
> * The line: “HTTP header fields...the internet system.” does not clearly explain the purpose of Headers.
> * Again, adding an example and reducing texts that seem like “fun facts” might benefit the HTTP with REST section.

I intended for the doc to be more of a guide to learning HTTP, rather than a complete tutorial. For that purpose, I believe MDN is one of the right choices. Since MDN docs are humongous and a beginner needn't use all that it offers to get their job done right away, I've marked the what I felt important while linking their corresponding documentations on MDN. Not maintaining our own documentations regarding HTTP seemed the correct approach since it's already been done, quite extensively at that, and replicating the same information again felt crass and unreasonable. Most organisations take this approach including the major ones and I must say I agree with them [[ref](https://www.zdnet.com/article/developers-rejoice-microsoft-google-mozilla-are-putting-all-their-web-api-docs-in-one-place/)]. Do tell me if you think otherwise and what we should do instead.

> * Hyperlinking of text to be completed.

Please help me with this. Would you be willing to add a commit doing the same or commenting on the code where it's missing? Either would help.

> * The length and content structure of the document seems very well suited for a new joiner wanting to get introduced to the topic, while having an option to explore deeper with the hyperlinked resources within the article.

Thanks for the kind words. I meant to do exactly this.

**Comment by PrateeksGitHub** [comment]
Hi @vabshere 
I agree with the intent of making this doc a guide to learning HTTP, by which I understand - an introduction to the concept and scope of HTTP. while for a detailed tutorial using MDN. In fact, for that reason itself, I had suggested we remove certain points that act like "fun facts" and do not add to one's understanding of HTML. That way, more space could be created to elaborate on other pointers, if necessary. 
Either way, the examples I mentioned earlier are likely biased due to my understanding of HTML and my style of learning, and they do not seem to be adding negative value to the doc, so there is no strong reason to remove/replace them IMO.

Sure, I will try to get the hyperlinking done this week.

Thanks for taking feedback well! :)

**Comment by vabshere** [comment]
@PrateeksGitHub Valid point
I'll take feedback from more people on this particular matter due to its subjectivity
Can then revise it accordingly

**Comment by vabshere** [comment]
Hey @PrateeksGitHub 
Thanks for the commit. I didn't notice this was an issue.
But as a convention for this doc, can you try limiting the column width of a line not more than 80 in a new PR? For example, "REST is..." can begin on a new line [here](https://github.com/skit-ai/curriculum/blame/http-api/docs/http/index.md#L78).

**Comment by PrateeksGitHub** [comment]
It's done now, @vabshere!

**Pull request merged**
